// The duplication hunt, round 2: MID-TURN repairs. Round 1 (liveReplayDuplication)
// injected the FINAL page at every stream position and reproduced nothing — but a
// live repair fetches whatever log-store has materialized AT THAT MOMENT, and a
// mid-turn page annotates differently (an OTel user copy not yet ingested, a
// narration block not yet provably tooled). The prefix pages here are generated by
// log-store's own buildTurnModel over prefixes of the real captured events, so
// each is exactly what the server would have served then.
//
// The sweep: page P_j (materialization after j+1 events) injected at stream
// position p (client has folded events[0..p)), for every j < p — the page always
// at-or-behind the stream, which ingestion lag makes the realistic shape — plus
// j == p. No trailing final repair: the browser showed the bad state persisting,
// so the invariant must hold WITHOUT one.
import { describe, expect, it } from 'vitest';
import { createChatStore } from '../src/store/ChatStore.js';
import type { TurnModel } from '../src/net/types.js';
import type { WireEvent } from '../src/net/wireEvents.js';
import eventsFixture from './fixtures/duplication-session-events.json';
import prefixPages from './fixtures/duplication-session-prefix-pages.json';

const SID = 'br_1787615605129568013';
const USER_TEXT_PREFIX = 'Do these three steps one at a time';

const events: WireEvent[] = (eventsFixture as Array<Record<string, unknown>>).map((data) => ({
  id: String(data.event_id),
  type: String(data.type),
  data: data as never,
}));
const pages = prefixPages as TurnModel[];

function visibleTexts(store: ReturnType<typeof createChatStore>): string[] {
  const model = store.getState().turnsBySession.get(SID);
  if (!model) return [];
  return Object.values(model.entries)
    .filter((e) => !e.duplicate && e.text)
    .map((e) => e.text!) as string[];
}

const count = (texts: string[], prefix: string) =>
  texts.filter((t) => t.startsWith(prefix)).length;

describe('mid-turn repair interleavings', () => {
  it('one mid-turn repair never duplicates or hides content at stream end', () => {
    const failures: string[] = [];
    for (let p = 0; p <= events.length; p++) {
      for (let j = 0; j <= p && j < pages.length; j++) {
        const store = createChatStore();
        const a = store.getState().actions;
        a.appendOptimisticUser(SID, events[0]!.data.result?.text ?? '', 'creq_test');
        for (let i = 0; i < p; i++) a.applyTailEvent(SID, events[i]!);
        a.setTurns(SID, pages[j]!);
        for (let i = p; i < events.length; i++) a.applyTailEvent(SID, events[i]!);

        const texts = visibleTexts(store);
        const users = count(texts, USER_TEXT_PREFIX);
        const s1 = count(texts, 'Step 1:');
        const s2 = count(texts, 'Step 2:');
        if (users !== 1 || s1 !== 1 || s2 !== 1) {
          failures.push(`p=${p} j=${j}: user=${users} s1=${s1} s2=${s2}`);
        }
      }
    }
    expect(failures.slice(0, 12), `${failures.length} failing interleavings`).toEqual([]);
  });
});
